name: Test

on:
  push:
    branches:
      - '**'
      - '!dependabot/**'
    tags:
      - '**'
  pull_request:

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      min_version: 2.6

  test:
    name: "Ruby ${{ matrix.ruby-version }}: ${{ matrix.runs-on }}"
    needs: ruby-versions
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        runs-on:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        exclude:
          - {ruby-version: "2.6", runs-on: windows-latest}
          - {ruby-version: "2.7", runs-on: windows-latest}
          - {ruby-version: "3.0", runs-on: windows-latest}
          - {ruby-version: "3.1", runs-on: windows-latest}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install system dependencies
        if: |
          runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -V -y libcairo-dev
      - name: Install system dependencies
        if: |
          runner.os == 'macOS'
        run: |
          brew bundle
      - name: Install system dependencies
        if: |
          runner.os == 'Windows'
        run: |
          ridk exec pacman --sync --noconfirm mingw-w64-x86_64-cairo mingw-w64-ucrt-x86_64-cairo
      - name: Install dependencies
        run: |
          bundle install
      - name: Test
        run: |
          bundle exec rake

  windows-msys2:
    name: Windows ${{ matrix.msystem }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - msystem: CLANG64
            package-prefix: mingw-w64-clang-x86_64
            runner: windows-latest
          - msystem: CLANGARM64
            package-prefix: mingw-w64-clang-aarch64
            runner: windows-11-arm
          - msystem: MINGW32
            package-prefix: mingw-w64-i686
            runner: windows-latest
          - msystem: MINGW64
            package-prefix: mingw-w64-x86_64
            runner: windows-latest
          - msystem: UCRT64
            package-prefix: mingw-w64-ucrt-x86_64
            runner: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            base-devel
            ${{ matrix.package-prefix }}-cairo
            ${{ matrix.package-prefix }}-ruby
            ${{ matrix.package-prefix }}-toolchain
      - name: Install dependencies
        shell: msys2 {0}
        run: |
          bundle install
      - name: Test
        shell: msys2 {0}
        run: |
          bundle exec rake
